inherits:
  - duplicated
  - utils:base
  - utils:no-design-checks
  - utils:c2cwsgiutils
  - utils:fix

ignore-paths:
  - acceptance_tests

mypy:
  options:
    python-version: '3.10'

bandit:
  disable:
    - B603 # subprocess call - check for execution of untrusted input

ruff:
  options:
    target-version: py310
