services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./fast_api:/app
    ports:
      - 8085:8080
    environment:
      - BACKEND_CORS_ORIGINS
      - C2C__REDIS__URL=redis://redis:6379/0

  redis:
    image: bitnami/redis:7.4.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
