services:
  app:
    command:
      - uvicorn
      - fastapi_app.main:app
      - --host=0.0.0.0
      - --port=8080
      - --reload
      - --reload-dir=/venv/lib/python3.12/site-packages/
      - --reload-include=fastapi_app/**/*.py
      - --reload-include=c2casgiutils/**/*.py

    volumes:
      - fastapi_app:/venv/lib/python3.12/site-packages/fastapi_app
      - ../../c2casgiutils:/venv/lib/python3.12/site-packages/c2casgiutils
