name: Continuous integration

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    outputs:
      success: ${{ steps.success.outputs.success }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python3 -m pip install --requirement=.github/requirements.txt

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: "pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}\npre-commit-"
      - run: pre-commit run --all-files --color=always
      - run: git diff --exit-code --patch > /tmp/pre-commit.patch; git diff --color; git reset --hard || true
        if: failure()
      - uses: actions/upload-artifact@v4
        with:
          name: Apply pre-commit fix.patch
          path: /tmp/pre-commit.patch
          retention-days: 1
        if: failure()

      - id: success
        run: echo "::set-output name=success::true"

  test:
    name: Continuous integration
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    outputs:
      success: ${{ steps.success.outputs.success }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python3 -m pip install --requirement=.github/requirements.txt

      - name: Print environment information
        run: c2cciutils-env

      - name: Checks
        run: make prospector

      - name: Tests
        run: make pytest

      - name: Build
        run: docker build --tag=c2casgiutils .

      - name: Checks FastAPI app
        run: make acceptance_prospector

      - name: Test FastAPI app
        run: make acceptance_pytest

      - run: c2cciutils-docker-logs
        if: always()

      - uses: actions/upload-artifact@v4
        with:
          name: Acceptance-tests
          path: acceptance_tests/fastapi_app/results
          retention-days: 1
        if: failure()

      - id: success
        run: echo "::set-output name=success::true"

  publish:
    name: Publish
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    needs: [pre-commit, test]
    if: always()

    permissions:
      contents: write
      id-token: write

    steps:
      - run: '[[ "${{ needs.pre-commit.outputs.success }}" == "true" ]]'
      - run: '[[ "${{ needs.test.outputs.success }}" == "true" ]]'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python3 -m pip install --requirement=.github/requirements.txt

      - name: Publish
        run: tag-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
